# 行列演算の基礎

$\boldsymbol{w} = (\boldsymbol{X}^{T}\boldsymbol{X})^{-1}\boldsymbol{X}^{T}\boldsymbol{y}$

- ベクトルの定義
- 行列の定義
- 転置
- 逆行列
- 行列積

In [77]:
import numpy as np

In [79]:
# ベクトルの定義
x = np.array([[1],[2],[3]])
print(x)

[[1]
 [2]
 [3]]


In [80]:
# 行列の定義
X = np.array([[1,2],[3,4]])
print(X)

[[1 2]
 [3 4]]


In [81]:
# 転置
Xt = X.T
print(Xt)

[[1 3]
 [2 4]]


In [82]:
# 逆行列
# linear algebra:線形係数
X_inv = np.linalg.inv(X)
print(X_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [84]:
# 行列積
XX_inv = np.dot(X, X_inv)
print(XX_inv)

[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


# 演習問題

$\boldsymbol{X} = \begin{bmatrix}
1 & 2 & 3 \\
1 & 2 & 5 \\
1 & 3 & 4 \\
1 & 5 & 9 \\
\end{bmatrix}
,\boldsymbol{y} = \begin{bmatrix}
1\\
5\\
6\\
8\\
\end{bmatrix}
$ のとき

$\boldsymbol{w} = (\boldsymbol{X}^{T}\boldsymbol{X})^{-1}\boldsymbol{X}^{T}\boldsymbol{y}$

- Step1: $\boldsymbol{X}^{T}\boldsymbol{X}$
- Step2: $(\boldsymbol{X}^{T}\boldsymbol{X})^{-1}$
- Step3: $\boldsymbol{X}^{T}\boldsymbol{y}$
- Step4: $\boldsymbol{w} = (\boldsymbol{X}^{T}\boldsymbol{X})^{-1}\boldsymbol{X}^{T}\boldsymbol{y}$

In [85]:
# Xの定義
X = np.array([
    [1,2,3],
    [1,2,5],
    [1,3,4],
    [1,5,9],    
])
print(X)

[[1 2 3]
 [1 2 5]
 [1 3 4]
 [1 5 9]]


In [86]:
# yの定義
y = np.array([
    [1],
    [5],
    [6],
    [8],
])
print(y)

[[1]
 [5]
 [6]
 [8]]


In [87]:
# Step1:
XtX = np.dot(X.T, X)
print(XtX)

[[  4  12  21]
 [ 12  42  73]
 [ 21  73 131]]


In [91]:
# Step2:
XtX_inv =np.linalg.inv(XtX)
print(XtX_inv)

[[ 1.76530612 -0.39795918 -0.06122449]
 [-0.39795918  0.84693878 -0.40816327]
 [-0.06122449 -0.40816327  0.24489796]]


In [95]:
# Step3:
Xty = np.dot(X.T,y)
print(Xty)

[[ 20]
 [ 70]
 [124]]


In [97]:
# Step4:
w =np.dot(XtX_inv, Xty)
print(w)

[[-0.14285714]
 [ 0.71428571]
 [ 0.57142857]]


# Scikit-learnで実装

In [99]:
import sklearn

In [100]:
# 重回帰分析のみ
from sklearn.linear_model import LinearRegression

In [101]:
# モデルの宣言
model = LinearRegression()

In [103]:
# モデルの学習 ← パラメータの調整
model.fit(X, y)

LinearRegression()

In [105]:
# 調整後のパラメータ
model.coef_

array([[0.        , 0.71428571, 0.57142857]])

In [111]:
# 切片
model.intercept_

array([-0.14285714])

In [107]:
# 予測精度 ← 決定係数
model.score(X,y)

0.6923076923076925

In [108]:
# 予測値の計算
x = np.array([[1,2,3,]])

In [112]:
y_pred = model.predict(x)
y_pred

array([[3.]])